services:
  postgres:
    image: "postgres:latest"
    containername: "postgresdb"
    restart: always
      ports
        - "5432:5432"	
      environment
        POSTGRES_USER postgres
        POSTGRES_PASSWORD postgres
        POSTGRES_DB tacodb
      volumes
        - tacodb:/var/lib/postgresql/data
volumes:
  tacodb