services:
  postgres:
    image: "postgres:latest"
    container_name: postgresdb
    restart: always
    ports:
        - "5432:5432"	
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tacodb
    volumes:
      - tacodb:/var/lib/postgresql/data
    networks:
      - taconet
volumes: 
  tacodb:
    name: tacodb
networks:
  taconet: