services:
  postgres:
    image: postgres:latest
      container_name postgres-for-taco-cloud
      restart always
      ports
        - "5432:5432"	
      environment
        POSTGRES_USER postgres
        POSTGRES_PASSWORD postgres
        POSTGRES_DB tacodb
      volumes
        - tacodb:/var/lib/postgresql/data
volumes:
  tacodb