spring:
  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate
      local-datacenter: datacenter1
  application:
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:tacodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    name: tacocloud
    generate-unique-name: false
  thymeleaf:
    cache: false